<?php

namespace FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * annoncesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class annoncesRepository extends EntityRepository
{
}
