<?php

namespace FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * likesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class likesRepository extends EntityRepository
{
}
