<?php

namespace FrontendBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VusRepository extends EntityRepository
{
}
